// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuUrumyoBh-0I1hKL154ki75sDQUQ9AGQ',
    appId: '1:534352654403:web:746b8f9cf46c965cc0e4f6',
    messagingSenderId: '534352654403',
    projectId: 'luxe-b3676',
    authDomain: 'luxe-b3676.firebaseapp.com',
    storageBucket: 'luxe-b3676.appspot.com',
    measurementId: 'G-VPRVV241MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOdT4eLAn_lxTpcHtqhmVPAalTMLmG8Sw',
    appId: '1:534352654403:android:9a1d750a5e1536e3c0e4f6',
    messagingSenderId: '534352654403',
    projectId: 'luxe-b3676',
    storageBucket: 'luxe-b3676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2MZHuVE0FVWxdZaMKKrDKiNnHS_L9HC4',
    appId: '1:534352654403:ios:66137c6128eba194c0e4f6',
    messagingSenderId: '534352654403',
    projectId: 'luxe-b3676',
    storageBucket: 'luxe-b3676.appspot.com',
    iosBundleId: 'com.example.luxe',
  );
}
